### ISSUE TITLE
Create a sensor for each wishlist entry

### ISSUE THREAD

**Issue by murmelbahn** [custom-components/sensor.nintendo_wishlist#1]
Hi,

I'm using push notifications to notify myself if something from my wishlist is on sale.
If we had a sensor for each wishlist entry with additional attributes like price, percent of discount and so on you can make a more specific notification about what is on sale. The sensor state only needs to change to 1 if the item is on sale.

**Comment by boralyl** [comment]
I'm not sure if creating a sensor per game is the right thing to do.  Let me investigate the best way to do this as I agree that it would be useful to create automatons based on a state change.  The sensor itself does store all games on sale and includes all relevant information (for example these attributes are available: `{"on_sale": [{"box_art_url": "https://www.nintendo.com/content/dam/noa/en_US/games/switch/o/oninaki-switch/Switch_ONINAKI_box_eShop.png", "normal_price": 49.99, "percent_off": 10, "sale_price": 44.99, "title": "ONINAKI"}, {"box_art_url": "https://www.nintendo.com/content/dam/noa/en_US/games/switch/r/robbie-swifthand-and-the-orb-of-mysteries-switch/Switch_RobbieSwifthand_box_eShop.png", "normal_price": 17.99, "percent_off": 44, "sale_price": 9.99, "title": "Robbie Swifthand and the Orb of Mysteries"}], "unit_of_measurement": "on sale", "friendly_name": "Nintendo Wishlist", "icon": "mdi:nintendo-switch"}`)

**Comment by murmelbahn** [comment]
I was thinking about an own sensor per game because the geizhals component works similar:
https://www.home-assistant.io/components/geizhals/

I dont know if it is necessary to create a own sensor at the configuration side or something else.
It would be cool if we can get something like this.

But again, thank you for creating this.

**Comment by boralyl** [comment]
In the latest version, v2.1.0 I made the component create the wish list sensor as it does currently, but it will also create a sensor for each game in your wish list.  The state will be `0` if it's not on sale an `1` if it is on sale.  This should allow you to create automations per title or by monitoring any sensor whose name starts with `sensor.nintendo_wishlist_*`. 

![Screenshot from 2019-08-04 14-24-18](https://user-images.githubusercontent.com/109865/62429472-04176c80-b6c4-11e9-9d38-71477d79b06f.png)
