### ISSUE TITLE
Bad links in the HACS info page.

### ISSUE THREAD

**Issue by rjroch** [custom-components/sensor.nintendo_wishlist#11]
In the HACS info page, the RELEASE link for V3.0.3 goes to the wrong URL:

[https://github.com/boralyl/steam-wishlist/releases](url) rather than [https://github.com/custom-components/sensor.nintendo_wishlist/releases](url)

The Migration Guide link goes to:

[https://hass.fqdn.local/hacs/MIGRATION_TO_V3.md](url) rather than [https://github.com/custom-components/sensor.nintendo_wishlist/blob/master/MIGRATION_TO_V3.md](url)

**Comment by boralyl** [comment]
Thanks for reporting, this is fixed in master and will be released tomorrow as v3.1.0
