### ISSUE TITLE
Box art not showing in latest Home Assistant

### ISSUE THREAD

**Issue by vnijhuis** [custom-components/sensor.nintendo_wishlist#16]
**Describe the bug**
I do not see any box art with easy configuration

`type: 'custom:nintendo-wishlist-card'
entity: sensor.nintendo_wishlist
title: Switch Wishlist
image_style: backgroundart`

**To Reproduce**
just added Cuphead to the wishlist and after a restart the game shows without boxart. 
The html shows me:
background-size: 54% auto;background-position:100% 35%;background-image:url('https:https://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_Cuphead_image500w.jpg')

where i expect https: only once. 
In the chrome browsers network tab i see that the following url is loaded successfully with status code 200:
https://home.<myassistanturl>.nl/lovelace-vini/https://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_Cuphead_image500w.jpg 

**Expected behavior**
I think somehow the home assistant is added stuff to endpoints that should be checked? 

**Home Assistant Version:**
2020.12.7

**Comment by boralyl** [comment]
Which country are you using in your configuration?  I'm not seeing any issues with `US` set as the country but there are several different sources of data based on the selected country so that will help me track down the exact issue.

**Comment by vnijhuis** [comment]
Ah of-course forgot to mention that. I am using the country NL, Netherlands.
also added a small listing of my configuration.
```nintendo_wishlist:
  country: NL
  wishlist:
    - "The Legend of Zelda: Breath of the Wild"
    - "Mario Kart 8 Deluxe"
    - "Animal Crossing: New Horizons"
    - "Cuphead"```

**Comment by boralyl** [comment]
Thanks!  I'll look into this later today.

**Comment by vnijhuis** [comment]
Also no hurry. It's just a visual thing the sensor works ;) 
also the status in home assistant is with an extra https:
```matches:
  - box_art_url: >-
      https:https://cdn01.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_Cuphead_image500w.jpg
    nsuid: 70010000016329
    percent_off: 30
    title: Cuphead
    normal_price: '€ 19,99'
    sale_price: '€ 13,99'
unit_of_measurement: on sale
friendly_name: Cuphead
icon: 'mdi:nintendo-switch'

**Comment by boralyl** [comment]
Thanks for reporting!  This is fixed in the latest release: https://github.com/custom-components/sensor.nintendo_wishlist/releases/tag/v3.1.4

**Comment by vnijhuis** [comment]
Thanks for the quick fix. Even my wife is stoked about the looks on her phone. 
Great job.
