### ISSUE TITLE
Unexpected error fetching nintendo_wishlist data: 'discount_price'

### ISSUE THREAD

**Issue by fredrikbaberg** [custom-components/sensor.nintendo_wishlist#18]
**Describe the bug**
Error appears in log:
> Unexpected error fetching nintendo_wishlist data: 'discount_price'

**To Reproduce**
1. Restart Home Assistant.
2. Error appears in log after start.

**Expected behavior**
No error in log.

**Screenshots**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/nintendo_wishlist/eshop.py", line 106, in fetch_on_sale
    return await self.fetch_method()
  File "/config/custom_components/nintendo_wishlist/eshop.py", line 205, in fetch_eu
    pricing = await self.get_eu_pricing_data(list(games.keys()))
  File "/config/custom_components/nintendo_wishlist/eshop.py", line 239, in get_eu_pricing_data
    "sale_price": price["discount_price"]["amount"],
KeyError: 'discount_price'
```

**Home Assistant Version:**
core-2021.12.8

**Additional context**
Version 3.1.6

**Comment by boralyl** [comment]
@fredrikbaberg Could you share which country you have configured for the sensor?  Thanks for reporting!

**Comment by fredrikbaberg** [comment]
Sorry, I should have added the config I'm using from the start, but it is quite long.
Region is `GB`.
I've done some tests to provide a minimal example, the issue occurs if I include `doom`:
```
nintendo_wishlist:
  country: GB
  wishlist:
    - "Age of Calamity"
    - "Doom"
```

**Comment by boralyl** [comment]
This should be fixed in the latest release: https://github.com/custom-components/sensor.nintendo_wishlist/releases/tag/v3.1.7

**Comment by fredrikbaberg** [comment]
Thank you! That was quick.
I've updated and it seems to work.

Also, thank you for this component!
