### ISSUE TITLE
Sensor data empty from eshop

### ISSUE THREAD

**Issue by CygnusHyoga** [custom-components/sensor.nintendo_wishlist#19]
**Describe the bug**
Sensor are empty from data from the eshop. The "binary sensors" and the "sensor" Wishlist are created, but all sensor are empty with the attributes: on sale and matches (empty). Any help? Thanks!

**To Reproduce**

```
nintendo_wishlist:
  country: ES
  wishlist:
    - "Teenage Mutant Ninja Turtles: Shredder's Revenge"
    - "Advance Wars 1+2: Re-Boot Camp"
    - Kirby and the Forgotten Land
    - "Lego Star Wars: The Skywalker Saga"
    - Bayonetta 3
    - "Marvel's Midnight Suns"
    - "Mario + Rabbids: Sparks of Hope"
    - "The Legend of Zelda: Breath of the Wild"
```

**Home Assistant Version:**
Home assistant docker, installed add-on with HACS
Home Assistant 2022.2.1

**Comment by boralyl** [comment]
Could you point out a game that is on sale that isn't showing up?  As far as I can tell, none of those games are on sale in the eshop for your country.  If you add a game that is on sale, like "Hades", you will see the binary sensor with an `on` state and a single item in the wishlist sensor.  It would look something like this:

![image](https://user-images.githubusercontent.com/109865/152565429-2a95ffa2-d6e6-4f6c-86e2-c02caf275faf.png)

**Comment by CygnusHyoga** [comment]
Now it works perfectly with a game that is discounted. Sorry for the misunderstanding.

As a suggestion or for a feature request: it would also be interesting to show the games with a normal price, in order to monitor the release of new games (like upcoming releases). Maybe with some variable like "type: [standard,onsale]" for show games in the whislist.

Thanks again!
