### ISSUE TITLE
Error on GB country

### ISSUE THREAD

**Issue by fredrikbaberg** [custom-components/sensor.nintendo_wishlist#2]
When specifying GB as country I get an error, if I instead use DE it seems to work.

I've tried both with and without quotation marks around names, providing example:
```
### configuration.yaml example
sensor nintendo_wishlist:
  - platform: nintendo_wishlist
    country: GB
    wishlist:
      - "Wargroove"
      - "Mortal Kombat 11"
      - "Sid Meier's Civilization VI"
      - "The Way Remastered"
```

> nintendo_wishlist: Error on device update!
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
>     await entity.async_device_update(warning=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in async_device_update
>     await self.async_update()
>   File "/config/custom_components/nintendo_wishlist/sensor.py", line 130, in async_update
>     await self._eu_update()
>   File "/config/custom_components/nintendo_wishlist/sensor.py", line 160, in _eu_update
>     data = await resp.json(content_type=None)
>   File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1036, in json
>     return loads(stripped.decode(encoding))
>   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by boralyl** [comment]
Thanks for reporting!  This is now fixed in the latest version (v2.0.2)
