### ISSUE TITLE
Games without image

### ISSUE THREAD

**Issue by hudsonbrendon** [custom-components/sensor.nintendo_wishlist#20]
The integration works very well, however it is not bringing the game image

**Screenshots**

![image](https://user-images.githubusercontent.com/5201888/177264126-7499956b-a36e-42e3-8388-872b7ba067ff.png)

**Home Assistant Version:**

## System Health

version | core-2022.6.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.45
arch | x86_64
timezone | America/Recife

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.25.5
Stage | running
Available Repositories | 1092
Downloaded Repositories | 55

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17 de julho de 2022 21:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | us-east-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 109.3 GB
disk_used | 98.8 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.2), Node-RED (11.1.2), Studio Code Server (5.1.2), ESPHome (2022.3.1), Zigbee2MQTT (1.26.0-1), Cloudflare Tunnel (1.4.0), Transmission (dev), Samba share (10.0.0), Home Assistant Google Drive Backup (0.108.2), MariaDB (2.4.0), Network UPS Tools (0.11.0), AdGuard Home (4.6.0), Grafana (7.6.0), 3DPrinter (2021.11.7), Traccar (0.17.0), Grocy (0.18.2), Hass n8n (0.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 17
views | 11
mode | storage

</details>

<details><summary>MiWifi</summary>

version | 2.8.0
-- | --
192.168.31.1 (xiaomi.router.rm1800) | ok
192.168.31.214 (xiaomi.router.rm1800) | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 de julho de 2022 23:38
-- | --
current_recorder_run | 5 de julho de 2022 01:12
estimated_db_size | 962.28 MiB
database_engine | mysql
database_version | 10.4.19

</details>

<details><summary>Sonoff</summary>

version | 3.0.5 (200f243)
-- | --
cloud_online | 9 / 10
local_online | 9 / 9

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 2.1.0 (3d126a5)
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.6.9
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 14

</details>

**Comment by boralyl** [comment]
Thanks for reporting @hudsonbrendon Fixed in https://github.com/custom-components/sensor.nintendo_wishlist/releases/tag/v3.1.9
