### ISSUE TITLE
Please add Poland to supported countries/stores

### ISSUE THREAD

**Issue by spitfire** [custom-components/sensor.nintendo_wishlist#21]
Please add Poland to supported countries/stores

**Comment by boralyl** [comment]
Unfortunately I'm not sure the Poland region's website contains this information.  I took a quick look but couldn't find a list of games on sale.  If you could point me to a URL for the Poland region that contains pricing and sales information I could let you know for sure.

**Comment by spitfire** [comment]
Unfortunately I don't know either. Thanks for your reply.

**Comment by boralyl** [comment]
Bummer, if the Poland website starts showing that information in the future, let me know and I will add support :+1:
