### ISSUE TITLE
Startig Home Assistant with nintendo_wishlist takes a very long time

### ISSUE THREAD

**Issue by Nino-Bock** [custom-components/sensor.nintendo_wishlist#8]
The sensors work fine for me but restarting my Home Assistant takes a lot of time nintendo_wishlist is active.
Can this be fixed?
I really like the idea of your custom component and that's the only downside I see for now.

**Comment by boralyl** [comment]
Do you have any additional context on this issue?  All updates happen asynchronously and sensor updates are infrequent (once every 10 minutes) so adding this sensor should not effect the restart time with home assistant. 

I don't notice a difference in restart time when removing or adding this sensor.

**Comment by Nino-Bock** [comment]
Sorry for the late reply.

What do you need?
When adding the following piece of code to my configuration.yml file it takes a very long time to start:

`sensor:
- platform: nintendo_wishlist
  country: DE
  wishlist:
    - Katana ZERO
    - OKAMI HD
    - Mortal
    - Mushroom
    - Princess
    - Salt and Sanctuary
    - Dead Cells
    - Bloodstained
    - Dark Souls
    - Velocity X
    - "The Legend of Zelda: Breath of the Wild"
`

The logs did not provide any errors.

I'm using Home Assistant Core on my x86 Laptop in a python venv.

**Comment by boralyl** [comment]
Could you quantify what a long time to start means?  Are we talking about a minute to restart w/o the component and 5 minutes w/ the component?

I ran a few tests removing the component and restarting and doing the same with the component installed.  The difference in the restart times were negligible on `0.107.4`.

I'm not aware of anything the component is doing that could slow down start time, so I don't think there is much that I can do about this.  Fortunately, restarts shouldn't be that common of an operation, so you may just need to wait the extra time in order to use the component.

**Comment by Nino-Bock** [comment]
I'm at a different location now and it's working fine now.
It's an issue that on the other location I don't have IPv6 and some connection is waiting for a timeout and is blocking the whole application.
At least that's the problem on my Debian machines with apt  if I don't force them to use IPv4.

Due to Corona I won't go to the other location right now to test it and give you exact measurements.
I think it's about 20-30 seconds longer or so.

**Comment by boralyl** [comment]
I'm working on a re-write of this component to use best practices including the data update coordinator.  Currently if you have 5 games on your wish list, it will request the same data 5 times to see if each game is on sale.  The data update coordinator will update the data once per interval, then each game sensor can look at that data to determine if it's on sale or not.

This may fix the issue you are experiencing.

**Comment by boralyl** [comment]
The latest version (v3.0.0) now fetches data more efficiently.  Check out the [migration guide](https://github.com/custom-components/sensor.nintendo_wishlist/blob/master/MIGRATION_TO_V3.md) and let me know if this improves the start up time or not.

**Comment by Nino-Bock** [comment]
Hi,
it does not start for me.

`2020-04-14 10:08:40 ERROR (MainThread) [homeassistant.setup] Error during setup of component nintendo_wishlist
Traceback (most recent call last):
  File "/home/askarus/home-assistant/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/home/askarus/.homeassistant/custom_components/nintendo_wishlist/__init__.py", line 50, in async_setup
    update_interval=SCAN_INTERVAL,
TypeError: __init__() missing 1 required positional argument: 'request_refresh_debouncer'
`

**Comment by boralyl** [comment]
It looks like you are using a version of HA prior to v0.106.0.  I'll try adding a fix to make this component work with older versions of HA.  (The parameter mentioned there was required prior to v0.106)

**Comment by boralyl** [comment]
Which version of HA are you running?

**Comment by boralyl** [comment]
Unfortunately, it doesn't look like it's easy to use the new [`DataUpdateCoordinator`](https://developers.home-assistant.io/docs/integration_fetching_data#coordinated-single-api-poll-for-data-for-all-entities) to efficiently fetch data without requiring a newer version of home assistant.  I've updated the metadata for HACS to require a minimum version of `0.106.0`.

**Comment by Nino-Bock** [comment]
Thanks for the info.
I've tested it in my Development setup which was not updated for a while.
That explains it.
I'll update as soon as I've time and test it again.

**Comment by boralyl** [comment]
Closing this for now since there have been quite a few changes since this was reported.  Please open a new issue if you continue to experience issues.
