### ISSUE TITLE
GB Country Code Returning No Results

### ISSUE THREAD

**Issue by undulattice** [custom-components/sensor.nintendo_wishlist#9]
Hi.
Been trying to track down an installation problem with this for the past hour or so.
Just realised that it IS working correctly for the US country code, but not for GB country code.

Sonic Mania, for example, is on sale in both regions.
But does not show up when GB is the active country code.

Any ideas on how to fix?

Thanks

**Comment by boralyl** [comment]
Thanks for reporting!  I'll take a look at this later today.  Are there any errors in the homeassistant logs?

**Comment by undulattice** [comment]
Nothing in the logs that I can see. :-/

**Comment by boralyl** [comment]
Ok, well sounds like it shouldn't be hard to reproduce.  Could you also post your configuration?

**Comment by undulattice** [comment]
In configuration.yaml

nintendo_wishlist:
  country: GB
  wishlist:
    - Katana ZERO
    - Oninaki
    - Observer
    - Okami HD
    - Sonic
    - "The Legend of Zelda: Breath of the Wild"

**Comment by boralyl** [comment]
I was able to reproduce the issue, it should be an easy fix.  The component is only fetching the first 500 games on sale.  There are currently nearly 1000 on sale in the GB eshop, so the component just needs to be updated to fetch all of the results.

**Comment by undulattice** [comment]
Ah ok.
Good catch! :-)

**Comment by undulattice** [comment]
Just tested this by changing the number of returned rows in the component to 5000 and getting results as expected. :-)

**Comment by boralyl** [comment]
:+1: Just pushed a new release with the fix included: [v3.0.1](https://github.com/custom-components/sensor.nintendo_wishlist/releases).  It should appear in HACS shortly.

**Comment by undulattice** [comment]
👍

**Comment by undulattice** [comment]
New issue since update. Hopefully a quick one...

Log file reporting:
Setup failed for nintendo_wishlist: Unable to import component: cannot import name 'ResultsDict' from 'custom_components.nintendo_wishlist.types' (/config/custom_components/nintendo_wishlist/types.py)

**Comment by boralyl** [comment]
Whoops, you are right, forgot to commit that change.  Should be fixed in v3.0.2

**Comment by undulattice** [comment]
Yup. Sorted. :-)
